// Audit module constants

export const AUDIT_ACTIONS = {
  // Auth actions
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_MFA_SETUP: 'AUTH_MFA_SETUP',
  AUTH_MFA_VERIFY: 'AUTH_MFA_VERIFY',
  AUTH_PASSWORD_CHANGE: 'AUTH_PASSWORD_CHANGE',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_SESSION_REVOKE: 'AUTH_SESSION_REVOKE',

  // User actions
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',

  // Doctor actions
  DOCTOR_VERIFY: 'DOCTOR_VERIFY',
  DOCTOR_REJECT: 'DOCTOR_REJECT',
  DOCTOR_PROFILE_UPDATE: 'DOCTOR_PROFILE_UPDATE',

  // Patient actions
  PATIENT_PROFILE_UPDATE: 'PATIENT_PROFILE_UPDATE',

  // Appointment actions
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_CONFIRM: 'APPOINTMENT_CONFIRM',
  APPOINTMENT_START: 'APPOINTMENT_START',
  APPOINTMENT_COMPLETE: 'APPOINTMENT_COMPLETE',
  APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',
  APPOINTMENT_REFUND: 'APPOINTMENT_REFUND',

  // Payment actions
  PAYMENT_INTENT_CREATE: 'PAYMENT_INTENT_CREATE',
  PAYMENT_ATTEMPT: 'PAYMENT_ATTEMPT',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUND: 'PAYMENT_REFUND',
  PAYMENT_CHARGEBACK: 'PAYMENT_CHARGEBACK',

  // Withdrawal actions
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_VALIDATE: 'WITHDRAWAL_VALIDATE',
  WITHDRAWAL_SCHEDULE: 'WITHDRAWAL_SCHEDULE',
  WITHDRAWAL_PROCESS: 'WITHDRAWAL_PROCESS',
  WITHDRAWAL_COMPLETE: 'WITHDRAWAL_COMPLETE',
  WITHDRAWAL_FAIL: 'WITHDRAWAL_FAIL',
  WITHDRAWAL_CANCEL: 'WITHDRAWAL_CANCEL',

  // Medical record actions
  RECORD_VIEW: 'RECORD_VIEW',
  RECORD_ENTRY_CREATE: 'RECORD_ENTRY_CREATE',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_SIGN: 'DOCUMENT_SIGN',

  // Prescription actions
  PRESCRIPTION_CREATE: 'PRESCRIPTION_CREATE',
  PRESCRIPTION_UPDATE: 'PRESCRIPTION_UPDATE',
  PRESCRIPTION_SIGN: 'PRESCRIPTION_SIGN',
  PRESCRIPTION_SNCR_REGISTER: 'PRESCRIPTION_SNCR_REGISTER',
  PRESCRIPTION_CANCEL: 'PRESCRIPTION_CANCEL',

  // Telehealth actions
  VIDEO_SESSION_JOIN: 'VIDEO_SESSION_JOIN',
  VIDEO_SESSION_LEAVE: 'VIDEO_SESSION_LEAVE',
  VIDEO_RECORDING_START: 'VIDEO_RECORDING_START',
  VIDEO_RECORDING_STOP: 'VIDEO_RECORDING_STOP',
  VIDEO_TRANSCRIPTION_START: 'VIDEO_TRANSCRIPTION_START',

  // Order actions
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_PAYMENT: 'ORDER_PAYMENT',
  ORDER_PROCESS: 'ORDER_PROCESS',
  ORDER_SHIP: 'ORDER_SHIP',
  ORDER_DELIVER: 'ORDER_DELIVER',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_REFUND: 'ORDER_REFUND',

  // Pharmacy actions
  PHARMACY_CREATE: 'PHARMACY_CREATE',
  PHARMACY_UPDATE: 'PHARMACY_UPDATE',
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',

  // Consent actions
  CONSENT_ACCEPT: 'CONSENT_ACCEPT',
  CONSENT_REVOKE: 'CONSENT_REVOKE',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

// Actions that are considered sensitive and require immutable logging
export const SENSITIVE_ACTIONS = [
  AUDIT_ACTIONS.PAYMENT_APPROVED,
  AUDIT_ACTIONS.PAYMENT_REFUND,
  AUDIT_ACTIONS.PAYMENT_CHARGEBACK,
  AUDIT_ACTIONS.WITHDRAWAL_REQUEST,
  AUDIT_ACTIONS.WITHDRAWAL_COMPLETE,
  AUDIT_ACTIONS.RECORD_VIEW,
  AUDIT_ACTIONS.DOCUMENT_VIEW,
  AUDIT_ACTIONS.PRESCRIPTION_SIGN,
  AUDIT_ACTIONS.VIDEO_RECORDING_START,
] as const;
